[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["openai", "pdfjs-dist"]

[dev]
  functions = "netlify/functions"
  functionsPort = 9999
  # Increased timeout for local dev (OpenAI Vision can take 15-20s)
  # Value is in milliseconds
  timeout = 30

[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200